#!/usr/bin/env bash
# Recover an interrupted E2E run using the persistent run.env + Terraform state.
set -Eeuo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <state-dir>" >&2
  exit 2
fi

STATE_DIR="$(cd "$1" && pwd)"
ENV_FILE="$STATE_DIR/run.env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: missing $ENV_FILE" >&2
  exit 2
fi

# The file is generated by run.sh from validated resource identifiers and
# contains no credentials.
# shellcheck disable=SC1090
source "$ENV_FILE"

: "${PROJECT:?}"
: "${REGION:?}"
: "${ZONE:?}"
: "${RUN_ID:?}"
: "${POOL:?}"
: "${TF_DIR:?}"

rows="$(gcloud compute instances list --project "$PROJECT" \
  --filter="tags.items:pool-${POOL}" \
  --format='value(name,zone.basename())' 2>/dev/null || true)"
if [[ -n "$rows" ]]; then
  while IFS=$'\t' read -r name zone; do
    [[ -n "$name" && -n "$zone" ]] || continue
    echo "Deleting exact-tag pool VM $name ($zone)..."
    gcloud compute instances delete "$name" --project "$PROJECT" \
      --zone "$zone" --quiet
  done <<< "$rows"
fi

if [[ -f "$TF_DIR/terraform.tfstate" ]]; then
  DRIVER_MACHINE_TYPE="${DRIVER_MACHINE_TYPE:-e2-standard-2}"
  terraform -chdir="$TF_DIR" destroy -auto-approve \
    -var="project_id=$PROJECT" \
    -var="region=$REGION" \
    -var="zone=$ZONE" \
    -var="run_id=$RUN_ID" \
    -var="driver_machine_type=$DRIVER_MACHINE_TYPE"
fi

remaining="$(gcloud compute instances list --project "$PROJECT" \
  --filter="tags.items:pool-${POOL} OR labels.run_id=${RUN_ID}" \
  --format='value(name)' 2>/dev/null || true)"
if [[ -n "$remaining" ]]; then
  echo "error: matching instances remain: $remaining" >&2
  exit 1
fi

echo "Cleanup complete for $RUN_ID."
